#!/bin/bash

DOCKER_TAG=$1
APP_NAME=$(grep 'app:' mix.exs | sed -e 's/\[//g' -e 's/ //g' -e 's/app://' -e 's/[:,]//g')
APP_VERSION=$(grep 'version:' mix.exs | cut -d '"' -f2)
MIX_ENV=prod
CONTAINER=$DOCKER_USERNAME/$APP_NAME:$DOCKER_TAG

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

docker build --build-arg APP_NAME=$APP_NAME --build-arg APP_VERSION=$APP_VERSION -t $CONTAINER .
docker push $CONTAINER
